### ISSUE TITLE
flake8 errors still reported with flymake-ruff in use

### ISSUE THREAD

**Issue by hardaker** [erickgnavar/flymake-ruff#13]
I definitely do get ruff related errors when I use the standard `eglot` related config per the readme.  The problem is that I also still get `flake8` related warnings as well (most specifically -- line too long).  I have a `project.toml` file that specifically tells ruff to ignore these, so my ruff output is clean.

I *think* (ie, I started chasing code but failed to finish) that we might want to disable `flymake` from using other tools as well (possibly with an option config)?  Oddly, I tried this:

    (setq python-flymake-command '("cat" "/dev/null"))

but it didn't work (IE, I still got flake8 errors).

**Comment by erickgnavar** [comment]
Can you try this:

```elisp
(with-eval-after-load 'python
  (setq-local flymake-diagnostic-functions (delete 'python-flymake flymake-diagnostic-functions)))
```

It will remove default python flymake function so only `flymake-ruff` will be working

**Comment by hardaker** [comment]
Nope, didn't work.

**Comment by erickgnavar** [comment]
@hardaker does the solution proposed by @rweir fixed your problem? It seems that this problem is related to `eglot` rather than `flymake-ruff` 🤔

**Comment by erickgnavar** [comment]
Closed by inactivity

**Comment by hardaker** [comment]
Ugh, sorry for the delay.  The solution was complex and my work took over my life for a bit.  I'll try the proposed solution, but I think I need to read a lot first.  The bug should stay closed, certainly, as the source of the problem is understood at least.
