### ISSUE TITLE
flymake-ruff shows warnings in other modes

### ISSUE THREAD

**Issue by schmir** [erickgnavar/flymake-ruff#16]
I'm using eglot and both python and clojure modes. I've configured flymake-ruff according to the documentation with
```elisp
(add-hook 'eglot-managed-mode-hook 'flymake-ruff-load)
```

I end up with ruff warnings for my clojure code! When I use the following code, everything works as expected: 

```elisp
  (add-hook 'eglot-managed-mode-hook
            (lambda()
              (when (derived-mode-p 'python-base-mode)
                (flymake-ruff-load))))
```

**Comment by erickgnavar** [comment]
Hi, thanks for reporting this, can you make a PR to fix that in the documentation?

**Comment by schmir** [comment]
I did dig a bit deeper into the issue. There was already PR #9 that tried to fix the issue with this [commit](https://github.com/erickgnavar/flymake-ruff/pull/9/commits/5fc7006d0d876347eea26bb93a74135a93a51682).

I did find the following [blog post on flymake-clippy](https://www.mgmarlow.com/words/2023-06-17-flymake-clippy/), which describes the actual problem. The [flymake-clippy readme](https://github.com/mgmarlow/flymake-clippy/tree/main) contains instructions on how to setup the plugin with eglot.

**Comment by erickgnavar** [comment]
I added the change from the PR your mentioned, thanks for the report
