### ISSUE TITLE
Rerun with --fix

### ISSUE THREAD

**Issue by jgarte** [erickgnavar/flymake-ruff#8]
WDYT about adding an explicit command to rerun with `--fix`?

**Comment by erickgnavar** [comment]
That's out of scope, to use a formatter it can be done using [reformatter.el](https://melpa.org/#/reformatter), for example I have this in my config to sort imports

```emacs-lisp
(reformatter-define python-sort-imports
  :program "ruff"
  :args '("--fix" "--select" "I001" "-")
  :group 'python)
```

This will create some functions that can be called to format the entire buffer or a region, for example

```emacs-lisp
(python-sort-imports-region)
```

**Comment by jgarte** [comment]
Cool, thanks for sharing
